### ISSUE TITLE
Cannot compile using stock Ubuntu 16.04

### ISSUE THREAD

**Issue by CallumDev** [Librelancer/Librelancer#8]
Mono 4.2 on Ubuntu 16.04 fails to compile with:
`CSC: error CS0518: The predefined type 'System.Object' is not defined or imported`

Investigate as to why. For now this can be worked around by installing Xamarin's mono package.

The bug has already been reported on launchpad: https://bugs.launchpad.net/ubuntu/+source/mono/+bug/1565327

**Comment by CallumDev** [comment]
This is now no longer relevant as the .NET Core SDK is used for compiling.
